language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - hhvm

before_script:
    - composer install --prefer-dist --dev
    - pear install pear/PHP_CodeSniffer
    - phpenv rehash

script:
    - phpcs --standard=phpcs.xml  src/

notifications:
  email: false

matrix:
  allow_failures:
    - php: hhvm
